// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMfjJ9rC--mOLJH-TjBk1LcX1YVf38C_g',
    appId: '1:703178842530:web:0f066641eaefde126012fb',
    messagingSenderId: '703178842530',
    projectId: 'billiard-manage',
    authDomain: 'billiard-manage.firebaseapp.com',
    storageBucket: 'billiard-manage.firebasestorage.app',
    measurementId: 'G-KFF6WQ6YM1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7aePxam_I692XzJNKZq503JAbNGfS6JM',
    appId: '1:703178842530:android:bf07f5abdad6746e6012fb',
    messagingSenderId: '703178842530',
    projectId: 'billiard-manage',
    storageBucket: 'billiard-manage.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuMga8BGQ2VhhemagmDvcyC8UYZG-bNoA',
    appId: '1:703178842530:ios:4dd58d7d7c978c966012fb',
    messagingSenderId: '703178842530',
    projectId: 'billiard-manage',
    storageBucket: 'billiard-manage.firebasestorage.app',
    iosBundleId: 'com.example.billiardtm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuMga8BGQ2VhhemagmDvcyC8UYZG-bNoA',
    appId: '1:703178842530:ios:4dd58d7d7c978c966012fb',
    messagingSenderId: '703178842530',
    projectId: 'billiard-manage',
    storageBucket: 'billiard-manage.firebasestorage.app',
    iosBundleId: 'com.example.billiardtm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMfjJ9rC--mOLJH-TjBk1LcX1YVf38C_g',
    appId: '1:703178842530:web:3fd95e7425e8979b6012fb',
    messagingSenderId: '703178842530',
    projectId: 'billiard-manage',
    authDomain: 'billiard-manage.firebaseapp.com',
    storageBucket: 'billiard-manage.firebasestorage.app',
    measurementId: 'G-D60SL94S4S',
  );
}